### ISSUE TITLE
Cant run basic example

### ISSUE THREAD

**Issue by manuporto** [supasate/connected-react-router#40]
I'm running `yarn` and then `npm run dev` but I receive the following errors:

```
> connected-react-router-example-basic@1.0.0 dev /Users/***/Documents/connected-react-router/examples/basic
> node server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at Function.listen (/Users/ms0366/Documents/connected-react-router/examples/basic/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/***/Documents/connected-react-router/examples/basic/server.js:22:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.4.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! connected-react-router-example-basic@1.0.0 dev: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the connected-react-router-example-basic@1.0.0 dev script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the connected-react-router-example-basic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs connected-react-router-example-basic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls connected-react-router-example-basic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/***/.npm/_logs/2017-03-06T19_14_06_653Z-debug.log
```
I also leave the log as requested.

[2017-03-06T19_14_06_653Z-debug.log.zip](https://github.com/supasate/connected-react-router/files/822208/2017-03-06T19_14_06_653Z-debug.log.zip)

**Comment by manuporto** [comment]
I'm sorry, I didn't read the Error.
